version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/fleet-client"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: "develop"  
    open-pull-requests-limit: 10