version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/fleet-client"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10
    groups:
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
          - "typescript-eslint"

  - package-ecosystem: "gradle"
    directory: "/backend"
    schedule:
      interval: "weekly"
    target-branch: "develop"  
    open-pull-requests-limit: 10